### ISSUE TITLE
TidyRWeek5

### ISSUE THREAD

**Issue by loreabad6** [rroday/TidyTuesday#1]
Hi Rachel! Nice viz you made for Tidy Tuesday this week! 😄 

I was curious about why it took you so long to plot the polygons for the map, and also why some didn't show! So I took a look at your code. I have some recommendations for you:

1. Have you heard about [`sf`](https://github.com/r-spatial/sf)? It is a package to handle vector data in R, and comes really useful when plotting maps. If you are on windows, installation should not be a big problem other than installing Rtools as well. If you decide to use it, you can replace this peace of code: 
``` r
# Get world map 
world_map <- map_data("world")
```

With this:

``` r
# Alternative: use sf!
library(sf)
library(rnaturalearth) # package to access world data in vector format
world <- ne_countries(scale = "medium", returnclass = "sf") %>% 
  select(admin) # otherwise you get a lot of extra columns
```

2.  Now let's go to why the rest of your countries are not there. In your code you do the following join:
``` r
# Join lat/lon to plastics df
pmelt3 <- left_join(pmelt2, world_map, by = 'region')
```
But, this will leave you only with the world data that match your plastic data, and hence all the other data is gone. 

Here bellow I do also a join but with the world data first. I used the data I mentioned before since the format is already an sf object:
``` r
# Join your data
# Note that I do a left join with the world data first
# which will keep all the countries in and add the plastics info to those
# countries you selected
pmelt3 <- left_join(world, pmelt2, by = c("admin" = "region"))
```

3. Plot! `ggplot2` supports sf completely so you can replace this line:
``` r
 geom_polygon(aes(fill = Plastic.Count ), color = "white")+
```

with:

``` r
geom_sf(data = pmelt3, aes(fill = Plastic.Count), color = "white") +
```

You will end up with all your countries plotted, and those where no plastic was found will be NA colored in gray.  You can change this in the `scale_` line:

``` r
scale_fill_viridis_c(option = "C", name= "Plastic Count", na.value = "white")+
```

And voila! Here is what I got with these tweeks:
![image](https://user-images.githubusercontent.com/10034237/106308249-b9e35d00-6260-11eb-93d9-8dd0762088ef.png)

Hope this helps and keep it up!

**Comment by rroday** [comment]
> Hi Rachel! Nice viz you made for Tidy Tuesday this week! 😄
> 
> I was curious about why it took you so long to plot the polygons for the map, and also why some didn't show! So I took a look at your code. I have some recommendations for you:
> 
> 1. Have you heard about [`sf`](https://github.com/r-spatial/sf)? It is a package to handle vector data in R, and comes really useful when plotting maps. If you are on windows, installation should not be a big problem other than installing Rtools as well. If you decide to use it, you can replace this peace of code:
> 
> ```r
> # Get world map 
> world_map <- map_data("world")
> ```
> 
> With this:
> 
> ```r
> # Alternative: use sf!
> library(sf)
> library(rnaturalearth) # package to access world data in vector format
> world <- ne_countries(scale = "medium", returnclass = "sf") %>% 
>   select(admin) # otherwise you get a lot of extra columns
> ```
> 
> 1. Now let's go to why the rest of your countries are not there. In your code you do the following join:
> 
> ```r
> # Join lat/lon to plastics df
> pmelt3 <- left_join(pmelt2, world_map, by = 'region')
> ```
> 
> But, this will leave you only with the world data that match your plastic data, and hence all the other data is gone.
> 
> Here bellow I do also a join but with the world data first. I used the data I mentioned before since the format is already an sf object:
> 
> ```r
> # Join your data
> # Note that I do a left join with the world data first
> # which will keep all the countries in and add the plastics info to those
> # countries you selected
> pmelt3 <- left_join(world, pmelt2, by = c("admin" = "region"))
> ```
> 
> 1. Plot! `ggplot2` supports sf completely so you can replace this line:
> 
> ```r
>  geom_polygon(aes(fill = Plastic.Count ), color = "white")+
> ```
> 
> with:
> 
> ```r
> geom_sf(data = pmelt3, aes(fill = Plastic.Count), color = "white") +
> ```
> 
> You will end up with all your countries plotted, and those where no plastic was found will be NA colored in gray. You can change this in the `scale_` line:
> 
> ```r
> scale_fill_viridis_c(option = "C", name= "Plastic Count", na.value = "white")+
> ```
> 
> And voila! Here is what I got with these tweeks:
> ![image](https://user-images.githubusercontent.com/10034237/106308249-b9e35d00-6260-11eb-93d9-8dd0762088ef.png)
> 
> Hope this helps and keep it up!

Hi Lorena,

Thank you so much for the suggestion! I'm only just learning how to map in R and I really appreciate that you took time to suggest a better and more efficient method.

I know that my countries are missing because of the way I used left_join, but when I tried left_join with 'world' data first (as you have noted), it resulted in a data frame approximately 100 million rows long. I encountered this issue several times in many different ways and ultimately decided to leave countries with Coke PET=0 out of the map. However, when I run your code within this comment, it works perfectly.  Funny how that works sometimes.

Thank you again and I will update my code to reflect your suggestions!

**Comment by loreabad6** [comment]
> I know that my countries are missing because of the way I used left_join, but when I tried left_join with 'world' data first (as you have noted), it resulted in a data frame approximately 100 million rows long. 

Oh yes, this is certainly because of the way the `map_data()` output works. It is optimized for a let's say "outdated" way of handling spatial polygons in `ggplot2` where the standard way was to convert spatial objects into data frames to then be plotted. What you end up with is with one row for every single coordinate that makes up the polygon of each of your countries. So of course, plotting a very detailed world map with this approach will take a while. 

Luckily, since `ggplot2` started support for `sf` things are much easier now and it might give you a greater flexibility. I am happy the code flows better now for you!

> Thank you so much for the suggestion! I'm only just learning how to map in R and I really appreciate that you took time to suggest a better and more efficient method.

It's my pleasure! I think you are doing a great work with your dataviz learning with Tidy Tuesday and I am happy I can be part of the learning process! 😊
